<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>53e5fb15-24d8-4ab8-966c-c2f98aa7a918</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OptiCore.Application\OptiCore.Application.csproj" />
    <ProjectReference Include="..\OptiCore.Infrastructure\OptiCore.Infrastructure.csproj" />
  </ItemGroup>

</Project>
